name: Build and Upload to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install build dependencies
      working-directory: ./secsgml
      run: |
        python -m pip install --upgrade pip
        # Install Cython first since it's needed for build dependencies
        pip install cython
        pip install setuptools wheel twine build
    
    - name: Build package
      working-directory: ./secsgml
      run: |
        # Ensure Cython is available for build
        python -m pip list
        python -m build --wheel
        python -m build --sdist
    
    - name: Upload to PyPI
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: ./secsgml
      run: |
        twine upload dist/*